### ISSUE TITLE
Need to show the partners Name and also can control partners audio/Video

### ISSUE THREAD

**Issue by Sharad2390** [amirsanni/Video-Call-App-NodeJS#14]
Hi, 

Thanks for the wonderful code, as per my current requirement I need to show the joined user name, and also it is possible to manage partners' audio and video from the host.

**Comment by amirsanni** [comment]
1. Where do you want to show this joined user name?
2. You can manage remote user's audio.

**Comment by Sharad2390** [comment]
Leave the first point, I have done it on my end.

On the second point I want to mute partner audio and once I mute it, no one can listen to him/her.

**Comment by amirsanni** [comment]
Oh! That functionality is not there. If you mute a user, it will only impact your stream, not other users.

**Comment by Sharad2390** [comment]
I need that functionality, can you please help me out.

Thanks in advance.

**Comment by amirsanni** [comment]
A couple of things involved.

1. Can the muted user unmute himself?
2. Who can do this muting? Can anybody mute anybody?

My guess is, you will a sort of admin that will be able to do this. It's not as straightforward also because the users are directly connected to each other. Would have been easier if a media server was used.
