### ISSUE TITLE
Have to work for more than 4 person

### ISSUE THREAD

**Issue by Jaykantjha** [amirsanni/Video-Call-App-NodeJS#22]
Hi,
i found that its not working for more than 3 person in same room.
Even tested your demo link [https://chat.1410inc.xyz.](https://chat.1410inc.xyz.).
 When more than 3 person are connected then 
- same person is displayed multiple times 
- or video call of person get delayed

Sometime there is blank screen for room no video is displayed.
I tried to use in my project but not able to use.
Can you help ?

**Comment by amirsanni** [comment]
Hi @Jaykantjha, perhaps I should have mentioned this in the readme. The connection among participants uses mesh topology. So the number of users it can accommodate will be affected by the browsers and devices used. Ideally, it's suited to between maximum 3 and 4 participants due to browser limitations.

To make it work with more participants, you'll need a media server for routing medias among participants.

**Comment by karanshah0206** [comment]
But isn't WebRTC built basically to achieve excellent peer to peer interactions? In that case, implementing an external media server not only ruins the whole purpose, but it would also mean that we're not really doing peer to peer connection but instead using some external server off which videos are just running in playback.

**Comment by amirsanni** [comment]
@karanshah0206 No doubt, webRTC supports peer-to-peer with an unlimited number of users but do we have devices that can handle such connections? The simple answer is **NO**. Besides, there are WebRTC media servers out there.
